export const howItWorksData = [
  {
    img: "./home-page/how-it-works/workoutPlan.png",
    heading: "create your workout plan",
    desc: "Choose from ready-made plans or build your own based on your goals, fitness level, and schedule.",
  },
  {
    img: "./home-page/how-it-works/progress.png",
    heading: "track your progress",
    desc: "Log your workouts, monitor your stats, and celebrate every milestone along your fitness journey.",
  },
  {
    img: "./home-page/how-it-works/community.png",
    heading: "join the community",
    desc: "Share your journey, get support, and stay motivated with people who inspire you to keep going.",
  },
  {
    img: "./home-page/how-it-works/calender.png",
    heading: "stay consistent",
    desc: "Build lasting habits with reminders, streaks, and goals that keep you moving forward.",
  },
];

export const workouts = [
  {
    id: 1,
    img: "./home-page/featured/beginner-workout.png",
    title: "Beginner Workout",
    tag: "Perfect for New Starters",
    workouts_per_week: 3,
    minutes_per_day: "20-30",
    focus: "Full Body Focus",
  },
  {
    id: 2,
    img: "./home-page/featured/fat-loss.png",
    title: "Fat Loss Plan",
    tag: "Burn Fat & Get Lean",
    workouts_per_week: 4,
    minutes_per_day: "30-45",
    focus: "Cardio + Strength",
  },
  {
    id: 3,
    img: "./home-page/featured/muscle-gain.png",
    title: "Muscle Gain Plan",
    tag: "Build Strength & Size",
    workouts_per_week: "4-5",
    minutes_per_day: "45-60",
    focus: "Strength Training Focus",
  },
  {
    id: 4,
    img: "./home-page/featured/home-workout.png",
    title: "Home Workout",
    tag: "No Equipment Needed",
    workouts_per_week: "3-4",
    minutes_per_day: "20-40",
    focus: "Bodyweight Focus",
  },
];

[
  {
    id: 1,
    user: {
      name: "Olivia Martinez",
      avatar: "https://i.pravatar.cc/150?img=1",
    },
    created_at: "2024-01-15T09:30:00Z",
    time_ago: "1 hr",
    has_video: true,
    routine_name: "Olivia's Morning Routine",
    category: "Beginner Workout",
    exercises: [
      { name: "Goblet Squats", sets: 3, reps: 12, unit: "Reps" },
      { name: "Push-Ups", sets: 3, reps: 10, unit: "Reps" },
      { name: "Plank", sets: 3, reps: 30, unit: "Secs" },
    ],
    likes: 41,
    comments: 9,
    action_label: "Try This Routine",
  },
  {
    id: 2,
    user: {
      name: "Muscle Gain",
      avatar: "https://i.pravatar.cc/150?img=2",
    },
    created_at: "2024-01-13T14:00:00Z",
    time_ago: "2 days ago",
    has_video: true,
    routine_name: "Muscle Gain · Strength",
    category: "Muscle Gain",
    exercises: [
      { name: "Bench Press", sets: 4, reps: 8, unit: "Reps" },
      { name: "Pull-Ups", sets: 3, reps: 8, unit: "Reps" },
      { name: "Bicep Curls", sets: 3, reps: 10, unit: "Reps" },
    ],
    likes: 68,
    comments: 14,
    action_label: "View Plan",
  },
  {
    id: 3,
    user: {
      name: "Jake Thompson",
      avatar: "https://i.pravatar.cc/150?img=3",
    },
    created_at: "2024-01-15T07:00:00Z",
    time_ago: "3 hrs",
    has_video: false,
    routine_name: "Jake's HIIT Blast",
    category: "Cardio",
    exercises: [
      { name: "Burpees", sets: 4, reps: 15, unit: "Reps" },
      { name: "Jump Rope", sets: 3, reps: 60, unit: "Secs" },
      { name: "Mountain Climbers", sets: 3, reps: 20, unit: "Reps" },
    ],
    likes: 32,
    comments: 5,
    action_label: "Try This Routine",
  },
  {
    id: 4,
    user: {
      name: "Sara Lee",
      avatar: "https://i.pravatar.cc/150?img=4",
    },
    created_at: "2024-01-14T18:45:00Z",
    time_ago: "20 hrs",
    has_video: true,
    routine_name: "Sara's Yoga Flow",
    category: "Flexibility",
    exercises: [
      { name: "Downward Dog", sets: 3, reps: 45, unit: "Secs" },
      { name: "Warrior II", sets: 2, reps: 60, unit: "Secs" },
      { name: "Child's Pose", sets: 3, reps: 30, unit: "Secs" },
    ],
    likes: 55,
    comments: 11,
    action_label: "View Plan",
  },
  {
    id: 5,
    user: {
      name: "Marcus Reid",
      avatar: "https://i.pravatar.cc/150?img=5",
    },
    created_at: "2024-01-12T10:00:00Z",
    time_ago: "3 days ago",
    has_video: false,
    routine_name: "Marcus's Power Lift",
    category: "Strength · Advanced",
    exercises: [
      { name: "Deadlifts", sets: 5, reps: 5, unit: "Reps" },
      { name: "Squats", sets: 4, reps: 6, unit: "Reps" },
      { name: "Overhead Press", sets: 3, reps: 8, unit: "Reps" },
    ],
    likes: 89,
    comments: 22,
    action_label: "Try This Routine",
  },
  {
    id: 6,
    user: {
      name: "Priya Sharma",
      avatar: "https://i.pravatar.cc/150?img=6",
    },
    created_at: "2024-01-15T06:15:00Z",
    time_ago: "4 hrs",
    has_video: true,
    routine_name: "Priya's Core Crusher",
    category: "Core · Intermediate",
    exercises: [
      { name: "Crunches", sets: 3, reps: 20, unit: "Reps" },
      { name: "Leg Raises", sets: 3, reps: 15, unit: "Reps" },
      { name: "Russian Twists", sets: 3, reps: 20, unit: "Reps" },
    ],
    likes: 47,
    comments: 8,
    action_label: "View Plan",
  },
  {
    id: 7,
    user: {
      name: "Tom Walker",
      avatar: "https://i.pravatar.cc/150?img=7",
    },
    created_at: "2024-01-11T16:00:00Z",
    time_ago: "4 days ago",
    has_video: false,
    routine_name: "Tom's Fat Burn",
    category: "Weight Loss · Beginner",
    exercises: [
      { name: "Jumping Jacks", sets: 3, reps: 30, unit: "Reps" },
      { name: "High Knees", sets: 3, reps: 40, unit: "Secs" },
      { name: "Box Steps", sets: 4, reps: 12, unit: "Reps" },
    ],
    likes: 23,
    comments: 3,
    action_label: "Try This Routine",
  },
  {
    id: 8,
    user: {
      name: "Aisha Johnson",
      avatar: "https://i.pravatar.cc/150?img=8",
    },
    created_at: "2024-01-15T05:00:00Z",
    time_ago: "5 hrs",
    has_video: true,
    routine_name: "Aisha's Full Body Burn",
    category: "Full Body · Intermediate",
    exercises: [
      { name: "Lunges", sets: 3, reps: 12, unit: "Reps" },
      { name: "Dumbbell Rows", sets: 3, reps: 10, unit: "Reps" },
      { name: "Tricep Dips", sets: 3, reps: 15, unit: "Reps" },
    ],
    likes: 61,
    comments: 17,
    action_label: "View Plan",
  },
];
